// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.4
// source: wordrepo/wordrepo.proto

package wordrepo

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for SearchWord call.
type SearchWordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
}

func (x *SearchWordRequest) Reset() {
	*x = SearchWordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wordrepo_wordrepo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchWordRequest) ProtoMessage() {}

func (x *SearchWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wordrepo_wordrepo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchWordRequest.ProtoReflect.Descriptor instead.
func (*SearchWordRequest) Descriptor() ([]byte, []int) {
	return file_wordrepo_wordrepo_proto_rawDescGZIP(), []int{0}
}

func (x *SearchWordRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

// Response to SearchWord call.
type SearchWordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *SearchWordResponse) Reset() {
	*x = SearchWordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wordrepo_wordrepo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchWordResponse) ProtoMessage() {}

func (x *SearchWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wordrepo_wordrepo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchWordResponse.ProtoReflect.Descriptor instead.
func (*SearchWordResponse) Descriptor() ([]byte, []int) {
	return file_wordrepo_wordrepo_proto_rawDescGZIP(), []int{1}
}

func (x *SearchWordResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// Request for UpdateWordList call.
type UpdateWordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Words []string `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`
}

func (x *UpdateWordRequest) Reset() {
	*x = UpdateWordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wordrepo_wordrepo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWordRequest) ProtoMessage() {}

func (x *UpdateWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wordrepo_wordrepo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWordRequest.ProtoReflect.Descriptor instead.
func (*UpdateWordRequest) Descriptor() ([]byte, []int) {
	return file_wordrepo_wordrepo_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateWordRequest) GetWords() []string {
	if x != nil {
		return x.Words
	}
	return nil
}

type UpdateWordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdateWordResponse) Reset() {
	*x = UpdateWordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wordrepo_wordrepo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWordResponse) ProtoMessage() {}

func (x *UpdateWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wordrepo_wordrepo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWordResponse.ProtoReflect.Descriptor instead.
func (*UpdateWordResponse) Descriptor() ([]byte, []int) {
	return file_wordrepo_wordrepo_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateWordResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateWordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request for GetTopWords call
type GetTopWordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetTopWordRequest) Reset() {
	*x = GetTopWordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wordrepo_wordrepo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopWordRequest) ProtoMessage() {}

func (x *GetTopWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wordrepo_wordrepo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopWordRequest.ProtoReflect.Descriptor instead.
func (*GetTopWordRequest) Descriptor() ([]byte, []int) {
	return file_wordrepo_wordrepo_proto_rawDescGZIP(), []int{4}
}

type GetTopWordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*TopSearch `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetTopWordResponse) Reset() {
	*x = GetTopWordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wordrepo_wordrepo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopWordResponse) ProtoMessage() {}

func (x *GetTopWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wordrepo_wordrepo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopWordResponse.ProtoReflect.Descriptor instead.
func (*GetTopWordResponse) Descriptor() ([]byte, []int) {
	return file_wordrepo_wordrepo_proto_rawDescGZIP(), []int{5}
}

func (x *GetTopWordResponse) GetList() []*TopSearch {
	if x != nil {
		return x.List
	}
	return nil
}

type TopSearch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word  string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Count int64  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *TopSearch) Reset() {
	*x = TopSearch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wordrepo_wordrepo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopSearch) ProtoMessage() {}

func (x *TopSearch) ProtoReflect() protoreflect.Message {
	mi := &file_wordrepo_wordrepo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopSearch.ProtoReflect.Descriptor instead.
func (*TopSearch) Descriptor() ([]byte, []int) {
	return file_wordrepo_wordrepo_proto_rawDescGZIP(), []int{6}
}

func (x *TopSearch) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *TopSearch) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_wordrepo_wordrepo_proto protoreflect.FileDescriptor

var file_wordrepo_wordrepo_proto_rawDesc = []byte{
	0x0a, 0x17, 0x77, 0x6f, 0x72, 0x64, 0x72, 0x65, 0x70, 0x6f, 0x2f, 0x77, 0x6f, 0x72, 0x64, 0x72,
	0x65, 0x70, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x77, 0x6f, 0x72, 0x64, 0x72,
	0x65, 0x70, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x27, 0x0a, 0x11, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x57, 0x6f, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x2a, 0x0a, 0x12, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x29, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x77,
	0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x77, 0x6f, 0x72, 0x64,
	0x73, 0x22, 0x46, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x54, 0x6f, 0x70, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3d,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x72, 0x65, 0x70, 0x6f, 0x2e, 0x54, 0x6f,
	0x70, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x35, 0x0a,
	0x09, 0x54, 0x6f, 0x70, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x32, 0xaa, 0x02, 0x0a, 0x08, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x70,
	0x6f, 0x12, 0x61, 0x0a, 0x0a, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x57, 0x6f, 0x72, 0x64, 0x12,
	0x1b, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x72, 0x65, 0x70, 0x6f, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x77,
	0x6f, 0x72, 0x64, 0x72, 0x65, 0x70, 0x6f, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x57, 0x6f,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x12, 0x22, 0x10, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x2f, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x12, 0x5e, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x6f,
	0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x72, 0x65, 0x70,
	0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x72, 0x65, 0x70, 0x6f, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0b, 0x22, 0x09, 0x2f, 0x76, 0x31, 0x2f, 0x77,
	0x6f, 0x72, 0x64, 0x73, 0x12, 0x5b, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x57, 0x6f,
	0x72, 0x64, 0x73, 0x12, 0x1b, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x72, 0x65, 0x70, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x54, 0x6f, 0x70, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x72, 0x65, 0x70, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x6f, 0x70, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x11,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0b, 0x12, 0x09, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x6f, 0x72, 0x64,
	0x73, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x65, 0x64, 0x77, 0x61, 0x72, 0x64, 0x6c, 0x32, 0x30, 0x30, 0x34, 0x2f, 0x64, 0x65, 0x6c, 0x74,
	0x61, 0x74, 0x72, 0x65, 0x2d, 0x63, 0x6f, 0x64, 0x65, 0x2d, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x6f, 0x72, 0x64, 0x72, 0x65, 0x70,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wordrepo_wordrepo_proto_rawDescOnce sync.Once
	file_wordrepo_wordrepo_proto_rawDescData = file_wordrepo_wordrepo_proto_rawDesc
)

func file_wordrepo_wordrepo_proto_rawDescGZIP() []byte {
	file_wordrepo_wordrepo_proto_rawDescOnce.Do(func() {
		file_wordrepo_wordrepo_proto_rawDescData = protoimpl.X.CompressGZIP(file_wordrepo_wordrepo_proto_rawDescData)
	})
	return file_wordrepo_wordrepo_proto_rawDescData
}

var file_wordrepo_wordrepo_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_wordrepo_wordrepo_proto_goTypes = []interface{}{
	(*SearchWordRequest)(nil),  // 0: wordrepo.SearchWordRequest
	(*SearchWordResponse)(nil), // 1: wordrepo.SearchWordResponse
	(*UpdateWordRequest)(nil),  // 2: wordrepo.UpdateWordRequest
	(*UpdateWordResponse)(nil), // 3: wordrepo.UpdateWordResponse
	(*GetTopWordRequest)(nil),  // 4: wordrepo.GetTopWordRequest
	(*GetTopWordResponse)(nil), // 5: wordrepo.GetTopWordResponse
	(*TopSearch)(nil),          // 6: wordrepo.TopSearch
}
var file_wordrepo_wordrepo_proto_depIdxs = []int32{
	6, // 0: wordrepo.GetTopWordResponse.list:type_name -> wordrepo.TopSearch
	0, // 1: wordrepo.WordRepo.SearchWord:input_type -> wordrepo.SearchWordRequest
	2, // 2: wordrepo.WordRepo.UpdateWordList:input_type -> wordrepo.UpdateWordRequest
	4, // 3: wordrepo.WordRepo.GetTopWords:input_type -> wordrepo.GetTopWordRequest
	1, // 4: wordrepo.WordRepo.SearchWord:output_type -> wordrepo.SearchWordResponse
	3, // 5: wordrepo.WordRepo.UpdateWordList:output_type -> wordrepo.UpdateWordResponse
	5, // 6: wordrepo.WordRepo.GetTopWords:output_type -> wordrepo.GetTopWordResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wordrepo_wordrepo_proto_init() }
func file_wordrepo_wordrepo_proto_init() {
	if File_wordrepo_wordrepo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wordrepo_wordrepo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchWordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wordrepo_wordrepo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchWordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wordrepo_wordrepo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wordrepo_wordrepo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateWordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wordrepo_wordrepo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopWordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wordrepo_wordrepo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopWordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wordrepo_wordrepo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopSearch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wordrepo_wordrepo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wordrepo_wordrepo_proto_goTypes,
		DependencyIndexes: file_wordrepo_wordrepo_proto_depIdxs,
		MessageInfos:      file_wordrepo_wordrepo_proto_msgTypes,
	}.Build()
	File_wordrepo_wordrepo_proto = out.File
	file_wordrepo_wordrepo_proto_rawDesc = nil
	file_wordrepo_wordrepo_proto_goTypes = nil
	file_wordrepo_wordrepo_proto_depIdxs = nil
}
